### ISSUE TITLE
引用后，项目跑不起来了

### ISSUE THREAD

**Issue by Tim1104** [lkqm/spring-api-versioning#1]
添加@EnableApiVersioning 项目跑不起来了 v1.2.0 
Failed to introspect annotated methods on class com.github.lkqm.spring.api.version.ApiVersionAutoConfiguration

**Comment by lkqm** [comment]
1.2.0不支持spring2.x版本，已经发布1.3.0版本解决，国内同步有延迟.
```
<dependency>
  <groupId>com.github.lkqm</groupId>
  <artifactId>spring-api-versioning</artifactId>
  <version>1.3.0</version>
</dependency>
```
