### ISSUE TITLE
how to work this dependency

### ISSUE THREAD

**Issue by baggrek** [lkqm/spring-api-versioning#2]
im try set properties like 
# Version API
api.version.type=uri
api.version.uri-prefix=/api
api.version.uri-location=begin

# Controller 
@RestController
@RequestMapping("/config")
@ApiVersion("1")

after call api not found with base_url/v1/api/config

**Comment by lkqm** [comment]
Please confirm whether to restart the class to add annotation: @EnableApiVersioning ?

**Comment by baggrek** [comment]
thank for support,

<img width="435" alt="Screen Shot 2021-09-18 at 11 48 59 AM" src="https://user-images.githubusercontent.com/25553598/133872928-cc08dcd8-c63f-43d7-856f-4680d2c5bf05.png">

**Comment by lkqm** [comment]
Current supports spring boot 2.3.9.RELEASE, 2.5.3 maybe not work, I will test it and fix

**Comment by baggrek** [comment]
thanks for support

**Comment by lkqm** [comment]
In your case, the right url is: /api/v1/config
